Add ul component
gong-clone/programmers-clone pull request #20
Opened 2020-09-14 13:32 UTC by yg1110

- 채용 프로그램 ul 컴포넌트 추가.
- our-feature ul 컴포넌트 추가.
- storybook list 속성변경만 추가.
- list 자체를 추가하고싶었지만, 아직 문법을 이해하지 실패.

2020-09-15 01:12 UTC, tkddn204 commented on src/Components/Ul/index.tsx
> +import { Story } from '@storybook/react/types-6-0'
스토리는 스토리북 전용이기 때문에 `FC` 대신 사용해서는 안됩니다. `stories.tsx` 파일로 이동시켜주세요.

2020-09-15 01:15 UTC, tkddn204 commented on src/Pages/Main/index.tsx
> +)
테스트하는 부분을 실제 프로그램에 적용하지 않고 일단 스토리북으로 내보내는 방법은 어떨까요?

2020-09-15 01:17 UTC, tkddn204 reviewed
-

2020-09-15 01:19 UTC, tkddn204 requested changes
한 컴포넌트에는 하나 이상의 스토리가 있는 것을 권장합니다. 다음 커밋에 Li 컴포넌트의 스토리북 파일을 만들어주실수 있을까요?

2020-09-15 01:23 UTC, tkddn204 commented on src/Components/Li/index.tsx
> +}
이 리스트 컴포넌트들은 나중에 컴포지션으로 분리시키는 건 어떨까요?

2020-09-15 01:24 UTC, tkddn204 commented on src/Components/Ul/index.tsx
> +}
이 ul 컴포넌트들은 나중에 컴포지션으로 분리시키는 건 어떨까요?

2020-09-15 01:43 UTC, tkddn204 commented on src/Components/Ul/index.tsx
> +  list-style: ${(props) => props.listStyle};
아래 코드처럼 한 줄로 바꿔보는 건 어떨까요?
`list-style: ${(props) => props.listStyle && 'none'};`

2020-09-15 04:16 UTC, HyeanWoo commented on src/Components/Li/index.tsx
> +}
`PeriodLl`와 `TabItem`를 사용하지않고 불러오는 페이지에서 children을 넣어줘도 차이가 없어보입니다.

2020-09-15 04:17 UTC, HyeanWoo commented on src/Components/Ul/index.tsx
> +}
여기도 위에 질문과 같은 내용이네요

2020-09-15 15:01 UTC, tkddn204 approved these changes

2020-09-15 15:02 UTC, tkddn204 commented
좋습니다 👍

2020-09-16 04:10 UTC, HyeanWoo commented on src/Components/Li/index.tsx
> +  color?: '5F7F90'
여기에는 타입적는거 같습니다

2020-09-16 04:11 UTC, HyeanWoo approved these changes
확인했습니다 ~~

2020-09-16 04:16 UTC, yg1110 commented on src/Components/Li/index.tsx
> +  color?: '5F7F90'
아 다음 커밋에 바꿀게요.

2020-09-16 04:17 UTC, merged